// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilgnitasdfsfhysnyzrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZ25pdGFzZGZzZmh5c255enJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzE3NzgsImV4cCI6MjA2NDU0Nzc3OH0.eirtrwgboDR5uZc5NnTn-tx1Ox4ZV4nbRgstYoXRpYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);